name: mumush
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DI packages
  injectable: ^1.5.3
  get_it: ^7.2.0

  # Provider
  provider: ^6.0.3

  cupertino_icons: ^1.0.3
  flutter_svg: ^1.1.1+1
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.1.5
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # DI generators
  injectable_generator:
  build_runner:

  # Maps & Location
  google_maps_flutter: ^2.1.9
  location: ^4.3.0
  permission_handler: ^8.1.4+2

flutter:

  uses-material-design: true

    # Add assets from the images directory to the application.
  assets:
    - assets/ #folder indexing, all files will get indexed
    - assets/art/
    - assets/art/mumush.svg
    - assets/art/graund.png
    - assets/art/sky.png

  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/mapStyle/map_style.txt
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700
