name: mumush
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.8+8

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DI packages
  injectable: ^2.1.2
  get_it: ^7.2.0

  # Provider
  provider: ^6.0.3

  cupertino_icons: ^1.0.3
  flutter_svg: ^2.0.7
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.1.5
  font_awesome_flutter: ^9.2.0
  shared_preferences: ^2.0.15

  # Show local notifications
  flutter_local_notifications: ^15.1.0+1
  # Listen for notifications
  rxdart: ^0.27.7
  # Timezone
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0
  # DI generators
  injectable_generator:
  build_runner:

  # Networking
  http: ^1.1.0

  # Maps & Location
  google_maps_flutter: ^2.1.9
  location: ^5.0.1
  permission_handler: ^10.4.3
  url_launcher: ^6.0.10
  maps_launcher: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/art/mumush.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/art/mumush_foreground.png"

flutter:

  uses-material-design: true

    # Add assets from the images directory to the application.
  assets:
    - assets/art/
    - assets/art/concept_2023_Landing_mobile_base.png
    - assets/art/home_right.png
    - assets/art/home_left.png
    - assets/map/
    - assets/map/arboretum_stage.png
    - assets/map/artechno_tent.png
    - assets/map/orangePin.png
    - assets/map/arts&crafts.png
    - assets/map/av_install.png
    - assets/map/bar.png
    - assets/map/camping.png
    - assets/map/car_parking.png
    - assets/map/caravan_camping.png
    - assets/map/chill.png
    - assets/map/circulo_tent.png
    - assets/map/circus&yoga.png
    - assets/map/coffe&tea.png
    - assets/map/community_kitchen.png
    - assets/map/entrance.png
    - assets/map/fire.png
    - assets/map/fire_space.png
    - assets/map/food_court.png
    - assets/map/gargantua_stage.png
    - assets/map/healing.png
    - assets/map/info_panel.png
    - assets/map/info_point.png
    - assets/map/jam_stage.png
    - assets/map/kids_are.png
    - assets/map/medical_symbol.png
    - assets/map/nest.png
    - assets/map/stargate.png
    - assets/map/toilet.png
    - assets/map/toilets&showers.png
    - assets/map/uv_zone.png
    - assets/
    - assets/rawdata.json

  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/mapStyle/map_style.txt
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700