name: mumush
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DI packages
  injectable: ^1.5.3
  get_it: ^7.2.0

  # Provider
  provider: ^6.0.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # DI generators
  injectable_generator:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
